// Exercise metadata without candles (generated by `npm run catalog` into
// exercise-catalog.json). For anything that needs to know *about*
// exercises but not draw them. The practice page still uses the full data
// in src/data/exercises.ts.

import catalogJson from "@/data/exercise-catalog.json";
import type { Concept } from "@/lib/concepts";

export type ExerciseMeta = {
  exercise_id: string;
  concept: Concept;
  answer_type: "zone" | "level" | "choice" | "guided" | "free";
  difficulty: 1 | 2 | 3;
  answerLabel: string;
  timeframe: string;
  /** A real-data scenario (has provenance) rather than a constructed one. */
  real: boolean;
  trading_date: string | null;
  practice_ready: boolean;
};

export const catalog = catalogJson as ExerciseMeta[];

const byId = new Map(catalog.map((e) => [e.exercise_id, e]));

export function getExerciseMeta(id: string): ExerciseMeta | undefined {
  return byId.get(id);
}

/** Practice-ready exercises for a concept. */
export function getPracticeCatalog(concept: Concept): ExerciseMeta[] {
  return catalog.filter((e) => e.concept === concept && e.practice_ready);
}
